<?php

namespace app\modules\import\components;

/**
 * FixedUpload
 * Чинит баг в XUpload
 * @author  Виталий Евсюков
 * @package app\modules\import\components
 */

class FixedUpload extends \XUpload
{
    public $uploadView = 'xupload.views.upload';

    public $downloadView = 'xupload.views.download';

    public $formView = 'xupload.views.form';

    public function render($view, $data = null, $return = false)
    {
        if ($view === $this->formView) {
            \Yii::app()->clientScript->registerScript(
                __CLASS__ . '#' . $this->htmlOptions['id'] . '#fix',
                "jQuery('#{$this->htmlOptions['id']}').data('fileupload', " .
                "jQuery('#{$this->htmlOptions['id']}').data('blueimpUIFileupload'));",
                \CClientScript::POS_READY
            );
        }
        return parent::render($view, $data, $return); // TODO: Change the autogenerated stub
    }
}